FROM ghcr.io/wolfyreload/bazzite-wolfy:stable

COPY build-vm.sh /tmp/build-vm.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build-vm.sh && \
    ostree container commit

## NOTES:
# - /var/lib/alternatives is required to prevent failure with some RPM installs
# - All RUN commands must end with ostree container commit
#   see: https://coreos.github.io/rpm-ostree/container/#using-ostree-container-commit




